import { asUTCDate } from "~/lib/utils"
/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const publicImplementationTypeSchema = z.union([
  z.literal("children"),
  z.literal("hours"),
]);

export const publicTimescaleTypeSchema = z.union([
  z.literal("all_time"),
  z.literal("ten_year"),
  z.literal("five_year"),
  z.literal("year"),
  z.literal("quarter"),
  z.literal("month"),
  z.literal("week"),
  z.literal("day"),
  z.literal("daypart"),
]);

export const jsonSchema = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const graphqlPublicGraphqlArgsSchema = z.object({
  extensions: jsonSchema.optional(),
  operationName: z.string().optional(),
  query: z.string().optional(),
  variables: jsonSchema.optional(),
});

export const graphqlPublicGraphqlReturnsSchema = jsonSchema;

export const publicExecutorRowSchema = z.object({
  comments: z.string(),
  id: z.string().default(() => crypto.randomUUID()),
  name: z.string(),
});

export const publicExecutorInsertSchema = z.object({
  comments: z.string(),
  id: z.string().default(() => crypto.randomUUID()),
  name: z.string(),
});

export const publicExecutorUpdateSchema = z.object({
  comments: z.string().optional(),
  id: z.string().default(() => crypto.randomUUID()).optional(),
  name: z.string().optional(),
});

export const publicExecutorOccupiedRowSchema = z.object({
  end: z.string(),
  executor_id: z.string().default(() => crypto.randomUUID()),
  start: z.string(),
});

export const publicExecutorOccupiedInsertSchema = z.object({
  end: z.string(),
  executor_id: z.string().default(() => crypto.randomUUID()),
  start: z.string(),
});

export const publicExecutorOccupiedUpdateSchema = z.object({
  end: z.string().optional(),
  executor_id: z.string().default(() => crypto.randomUUID()).optional(),
  start: z.string().optional(),
});

export const publicExecutorOccupiedRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("executor_occupied_executor_id_executor_id_fk"),
    columns: z.tuple([z.literal("executor_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("executor"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTaskRowSchema = z.object({
  assigned_to: z.string().nullable(),
  comments: z.string(),
  expected: z.number(),
  id: z.string().default(() => crypto.randomUUID()),
  implementation: publicImplementationTypeSchema,
  name: z.string(),
  optimistic: z.number(),
  parent_id: z.string().default(() => crypto.randomUUID()),
  pessimistic: z.number(),
  timeframe_start: z.union([z.string(), z.date()]).transform((v) => asUTCDate(v + "Z")),
  timescale: publicTimescaleTypeSchema,
});

export const publicTaskInsertSchema = z.object({
  assigned_to: z.string().optional().nullable(),
  comments: z.string(),
  expected: z.number(),
  id: z.string().default(() => crypto.randomUUID()),
  implementation: publicImplementationTypeSchema,
  name: z.string(),
  optimistic: z.number(),
  parent_id: z.string().default(() => crypto.randomUUID()),
  pessimistic: z.number(),
  timeframe_start: z.union([z.string(), z.date()]).transform((v) => asUTCDate(v + "Z")),
  timescale: publicTimescaleTypeSchema,
});

export const publicTaskUpdateSchema = z.object({
  assigned_to: z.string().optional().nullable(),
  comments: z.string().optional(),
  expected: z.number().optional(),
  id: z.string().default(() => crypto.randomUUID()).optional(),
  implementation: publicImplementationTypeSchema.optional(),
  name: z.string().optional(),
  optimistic: z.number().optional(),
  parent_id: z.string().default(() => crypto.randomUUID()).optional(),
  pessimistic: z.number().optional(),
  timeframe_start: z.union([z.string(), z.date()]).transform((v) => asUTCDate(v + "Z")).optional(),
  timescale: publicTimescaleTypeSchema.optional(),
});

export const publicTaskRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("task_assigned_to_executor_id_fk"),
    columns: z.tuple([z.literal("assigned_to")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("executor"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("task_parent_id_task_id_fk"),
    columns: z.tuple([z.literal("parent_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("task"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export type PublicImplementationType = z.infer<
  typeof publicImplementationTypeSchema
>;
export type PublicTimescaleType = z.infer<typeof publicTimescaleTypeSchema>;
export type Json = z.infer<typeof jsonSchema>;
export type GraphqlPublicGraphqlArgs = z.infer<
  typeof graphqlPublicGraphqlArgsSchema
>;
export type GraphqlPublicGraphqlReturns = z.infer<
  typeof graphqlPublicGraphqlReturnsSchema
>;
export type PublicExecutorRow = z.infer<typeof publicExecutorRowSchema>;
export type PublicExecutorInsert = z.infer<typeof publicExecutorInsertSchema>;
export type PublicExecutorUpdate = z.infer<typeof publicExecutorUpdateSchema>;
export type PublicExecutorOccupiedRow = z.infer<
  typeof publicExecutorOccupiedRowSchema
>;
export type PublicExecutorOccupiedInsert = z.infer<
  typeof publicExecutorOccupiedInsertSchema
>;
export type PublicExecutorOccupiedUpdate = z.infer<
  typeof publicExecutorOccupiedUpdateSchema
>;
export type PublicExecutorOccupiedRelationships = z.infer<
  typeof publicExecutorOccupiedRelationshipsSchema
>;
export type PublicTaskRow = z.infer<typeof publicTaskRowSchema>;
export type PublicTaskInsert = z.infer<typeof publicTaskInsertSchema>;
export type PublicTaskUpdate = z.infer<typeof publicTaskUpdateSchema>;
export type PublicTaskRelationships = z.infer<
  typeof publicTaskRelationshipsSchema
>;
