/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const publicTaskStatusSchema = z.union([
  z.literal("pending"),
  z.literal("done"),
  z.literal("dropped"),
]);

export const jsonSchema = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const graphqlPublicGraphqlArgsSchema = z.object({
  extensions: jsonSchema.optional(),
  operationName: z.string().optional(),
  query: z.string().optional(),
  variables: jsonSchema.optional(),
});

export const graphqlPublicGraphqlReturnsSchema = jsonSchema;

export const publicTaskRowSchema = z.object({
  assigned_user: z.string().nullable(),
  blocked_by: z.number().nullable(),
  comments: z.string().nullable(),
  id: z.number(),
  name: z.string(),
  parent_id: z.number(),
  status: publicTaskStatusSchema,
  timeframe_end: z.string(),
  timeframe_start: z.string(),
});

export const publicTaskInsertSchema = z.object({
  assigned_user: z.string().optional().nullable(),
  blocked_by: z.number().optional().nullable(),
  comments: z.string().optional().nullable(),
  id: z.never().optional(),
  name: z.string(),
  parent_id: z.number(),
  status: publicTaskStatusSchema.optional(),
  timeframe_end: z.string(),
  timeframe_start: z.string(),
});

export const publicTaskUpdateSchema = z.object({
  assigned_user: z.string().optional().nullable(),
  blocked_by: z.number().optional().nullable(),
  comments: z.string().optional().nullable(),
  id: z.never().optional(),
  name: z.string().optional(),
  parent_id: z.number().optional(),
  status: publicTaskStatusSchema.optional(),
  timeframe_end: z.string().optional(),
  timeframe_start: z.string().optional(),
});

export const publicTaskRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("task_blocked_by_fkey"),
    columns: z.tuple([z.literal("blocked_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("task"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("task_parent_id_fkey"),
    columns: z.tuple([z.literal("parent_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("task"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export type PublicTaskStatus = z.infer<typeof publicTaskStatusSchema>;
export type Json = z.infer<typeof jsonSchema>;
export type GraphqlPublicGraphqlArgs = z.infer<
  typeof graphqlPublicGraphqlArgsSchema
>;
export type GraphqlPublicGraphqlReturns = z.infer<
  typeof graphqlPublicGraphqlReturnsSchema
>;
export type PublicTaskRow = z.infer<typeof publicTaskRowSchema>;
export type PublicTaskInsert = z.infer<typeof publicTaskInsertSchema>;
export type PublicTaskUpdate = z.infer<typeof publicTaskUpdateSchema>;
export type PublicTaskRelationships = z.infer<
  typeof publicTaskRelationshipsSchema
>;
