/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskDataTableRouteImport } from './routes/task-data-table'
import { Route as IndexRouteImport } from './routes/index'

const TaskDataTableRoute = TaskDataTableRouteImport.update({
  id: '/task-data-table',
  path: '/task-data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/task-data-table': typeof TaskDataTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/task-data-table': typeof TaskDataTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/task-data-table': typeof TaskDataTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/task-data-table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/task-data-table'
  id: '__root__' | '/' | '/task-data-table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskDataTableRoute: typeof TaskDataTableRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/task-data-table': {
      id: '/task-data-table'
      path: '/task-data-table'
      fullPath: '/task-data-table'
      preLoaderRoute: typeof TaskDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskDataTableRoute: TaskDataTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
