/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestVerticalRouteImport } from './routes/test/vertical'
import { Route as TestTaskDataTableRouteImport } from './routes/test/task-data-table'
import { Route as TestStatsRouteImport } from './routes/test/stats'
import { Route as TestResizableRouteImport } from './routes/test/resizable'
import { Route as TestHorizontalRouteImport } from './routes/test/horizontal'
import { Route as TestDndRouteImport } from './routes/test/dnd'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestVerticalRoute = TestVerticalRouteImport.update({
  id: '/test/vertical',
  path: '/test/vertical',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTaskDataTableRoute = TestTaskDataTableRouteImport.update({
  id: '/test/task-data-table',
  path: '/test/task-data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const TestStatsRoute = TestStatsRouteImport.update({
  id: '/test/stats',
  path: '/test/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResizableRoute = TestResizableRouteImport.update({
  id: '/test/resizable',
  path: '/test/resizable',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHorizontalRoute = TestHorizontalRouteImport.update({
  id: '/test/horizontal',
  path: '/test/horizontal',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDndRoute = TestDndRouteImport.update({
  id: '/test/dnd',
  path: '/test/dnd',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test/dnd': typeof TestDndRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/resizable': typeof TestResizableRoute
  '/test/stats': typeof TestStatsRoute
  '/test/task-data-table': typeof TestTaskDataTableRoute
  '/test/vertical': typeof TestVerticalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/dnd': typeof TestDndRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/resizable': typeof TestResizableRoute
  '/test/stats': typeof TestStatsRoute
  '/test/task-data-table': typeof TestTaskDataTableRoute
  '/test/vertical': typeof TestVerticalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test/dnd': typeof TestDndRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/resizable': typeof TestResizableRoute
  '/test/stats': typeof TestStatsRoute
  '/test/task-data-table': typeof TestTaskDataTableRoute
  '/test/vertical': typeof TestVerticalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test/dnd'
    | '/test/horizontal'
    | '/test/resizable'
    | '/test/stats'
    | '/test/task-data-table'
    | '/test/vertical'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/dnd'
    | '/test/horizontal'
    | '/test/resizable'
    | '/test/stats'
    | '/test/task-data-table'
    | '/test/vertical'
  id:
    | '__root__'
    | '/'
    | '/test/dnd'
    | '/test/horizontal'
    | '/test/resizable'
    | '/test/stats'
    | '/test/task-data-table'
    | '/test/vertical'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestDndRoute: typeof TestDndRoute
  TestHorizontalRoute: typeof TestHorizontalRoute
  TestResizableRoute: typeof TestResizableRoute
  TestStatsRoute: typeof TestStatsRoute
  TestTaskDataTableRoute: typeof TestTaskDataTableRoute
  TestVerticalRoute: typeof TestVerticalRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/vertical': {
      id: '/test/vertical'
      path: '/test/vertical'
      fullPath: '/test/vertical'
      preLoaderRoute: typeof TestVerticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/task-data-table': {
      id: '/test/task-data-table'
      path: '/test/task-data-table'
      fullPath: '/test/task-data-table'
      preLoaderRoute: typeof TestTaskDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/stats': {
      id: '/test/stats'
      path: '/test/stats'
      fullPath: '/test/stats'
      preLoaderRoute: typeof TestStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/resizable': {
      id: '/test/resizable'
      path: '/test/resizable'
      fullPath: '/test/resizable'
      preLoaderRoute: typeof TestResizableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/horizontal': {
      id: '/test/horizontal'
      path: '/test/horizontal'
      fullPath: '/test/horizontal'
      preLoaderRoute: typeof TestHorizontalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/dnd': {
      id: '/test/dnd'
      path: '/test/dnd'
      fullPath: '/test/dnd'
      preLoaderRoute: typeof TestDndRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestDndRoute: TestDndRoute,
  TestHorizontalRoute: TestHorizontalRoute,
  TestResizableRoute: TestResizableRoute,
  TestStatsRoute: TestStatsRoute,
  TestTaskDataTableRoute: TestTaskDataTableRoute,
  TestVerticalRoute: TestVerticalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
